### ISSUE TITLE
Salary map couldn't open on safari and Facebook browser

### ISSUE THREAD

**Issue by ttcat** [kiang/salary#1]

**Comment by ttcat** [comment]
![image](https://cloud.githubusercontent.com/assets/1935330/16827998/593017c4-49be-11e6-9137-0d4b91056101.png)

**Comment by kiang** [comment]
應該是 map-canvas height: 100%; 的問題，有建議的解法嗎？（我還沒真的用過 Mac XD ）

**Comment by ttcat** [comment]
加一個 min-height?

**Comment by kiang** [comment]
踹踹看？  - a55a6a1bcb5d829f35eff62e7ad2722c7594704a

**Comment by ttcat** [comment]
有點太大了，會沒辦法滑到下面。另外，會一直出現「此網頁發生問題，因此重新載入」，如果沒有人有 辦法幫忙，我下禮拜找時間測試細節看看。 :)

**Comment by kiang** [comment]
恩，麻煩了，我手邊目前沒有任何這樣的環境 XD

**Comment by kiang** [comment]
已經改版，所以就關閉囉
