### ISSUE TITLE
變異係數與標準差關係不為平方與方根關係

### ISSUE THREAD

**Issue by JefferyKu** [kiang/salary#3]
變異係數與標準差，為何兩者關係不為平方和方根關係？謝謝。
https://kiang.github.io/salary/map/#2016/playButton2/6502100-011

**Comment by kiang** [comment]
數字的顯示並不是透過程式計算，而是直接從財政部報告中取出，或許可以參考原始資料的報表
https://github.com/kiang/salary/tree/gh-pages/raw

**Comment by JefferyKu** [comment]
找到答案。

變異係數
變異數
兩者不同。變異數和標準差才為平方與方根關係。變異係數為標準差除以平均數。
ref: https://baike.baidu.com/item/变异系数
